from shiny import App, render, ui
from find_present_tense import search

app_ui = ui.page_fluid(
    ui.panel_title("Spanish Present Tense Finder"),
    ui.markdown("*Made by Gabriel Pišvejc.*"),
    ui.markdown("**Contact**: GabrielPisvejc@protonmail.com"),
    ui.markdown("[GitHub repository](https://github.com/GabrielZelva/spanish-present-tense-seacher)"),
    ui.input_radio_buttons(
        "text_type",
        "What text type is the file?",
        {"normal": "Normal text", "preseea": "PRESEEA"},
    ),
    ui.input_file("f", "Upload your text:", accept=[".txt"]),
    "Future tenses found:",
    ui.output_text_verbatim("text"),
)

def server(input, output, session):
    @render.text
    def text():

        files = input.f()
        if not files:

            logo = """
    ........................................................
    ..................;lx0KXNXKK0ko;........................
    ...............:dOXNMMMMMMMMMMWXOd:.....................
    ............'lONMMMMMMMMMMMMMMMMMMW0o'..................
    ...........:0WMMMMWXOxolllodxOXWMMMMW0c.................
    ..........oXMMMMW0l,..........,lOWMMMMNo................
    .........lNMMMMXo'...............lXMMMMNo...............
    ........,0MMMMNl..................cXMMMMK;..............
    ........lNMMMMO'..................'kMMMMWo..............
    ........lNMMMMk....................xMMMMWo..............
    ........,OWMMM0;..................,0MMMMNc..............
    .........,OWMMWk,................'xWMMMMO,..............
    ...........lONWW0c..............cOWMMMMK:...............
    .............;ldkko,.........,lONMMMMW0:................
    ..........................:oxXWMMMMMWKxdxkkkdl:'........
    .......................,o0WMMMMMMMMMWWWMWWWWMMWKd,......
    ....................'ckXMMMMMMMMMMMMMNkoc:;clkXMMKl.....
    ..................;d0WMMMMMMMMMMMMW0d;........;OWMXl....
    ...............'ckNMMMMMMMMMMMMMXkc'...........;0MMO....
    .............;dKWMMMMMMMMMMMMW0o,..............,OMM0....
    ..........,lONMMMMMMMMMMMWX0x:.................oNMWd....
    ........:xXWMMMMMMMMMMMNOl,.................,ckNMWk'....
    .....,lONMMMMMMMMMMMWKx:................'lx0XWWXOl......
    ...:xXWMMMMMMMMMMMNOl'....................,:cc:,........
    ..dNMMMMMMMMMMMWKd;.....................................
    ..,lOXWMMMMMWXkc'.......................................
    .....,:lloll:,..........................................
    ........................................................
            """

            return logo

        path = files[0]["datapath"]

        with open(path, "r", encoding="utf-8") as f:
            corpus = f.read()

        output = search(corpus, input.text_type())

        return output

app = App(app_ui, server)

if __name__ == "__main__":
    app.run()

